### ISSUE TITLE
provide SSL support for foreman_callback.py

### ISSUE THREAD

**Issue by MrRagga-** [dLobatog/foreman_ansible#1]
It is advised to run foreman with SSL support.
Thus it would be nice to add SSL support for the callback.

**Comment by dLobatog** [comment]
Thanks @MrRagga-  - just leaving a few notes here so I remember it:

api/v2/hosts/facts is a route protected by https://github.com/theforeman/foreman/blob/develop/app/controllers/concerns/foreman/controller/smart_proxy_auth.rb#L35

**Comment by dLobatog** [comment]
@MrRagga- Last version of the callback should allow you to set an SSL cert and key, please check it out :smile:
