### ISSUE TITLE
facts are partially uploaded

### ISSUE THREAD

**Issue by MrRagga-** [dLobatog/foreman_ansible#2]
The ansible script runs successfully, but only 4 facts are imported.

The foreman logfile logs:
2015-11-02T11:06:01 [app] [I] Started POST "/api/v2/hosts/facts" for 192.168.1.2 at 2015-11-02 11:06:01 +0100
2015-11-02T11:06:01 [app] [I] Processing by Api::V2::HostsController#facts as JSON
2015-11-02T11:06:01 [app] [I]   Parameters: {"name"=>"vs108", "_timestamp"=>"2015-11-02_110601_111051", "facts"=>"[FILTERED]", "apiv"=>"v2", :host=>{"name"=>"vs108"}}
2015-11-02T11:06:01 [app] [I] Import facts for 'vs108' completed. Added: 0, Updated: 1, Deleted 0 facts
2015-11-02T11:06:01 [app] [I] Completed 422 Unprocessable Entity in 65.5ms (Views: 0.5ms | ActiveRecord: 9.4ms

And only 4 facts are imported:
category
changed
ansible_facts
invocation

**Comment by MrRagga-** [comment]
{
  "name":"vs108.unstable.ipc4.rack.zone",
  "_timestamp":"2015-11-02_110601_111051",
  "facts": {"invocation": {"module_name": "setup", "module_args": ""}, "category": "OK", "_type": "ansible", "changed": false, "ansible_facts": {"facter_operatingsystem": "Debian", "facter_blockdevice_vdf_size": 107374182400, "module_setup": true, "facter_memoryfree_mb": "15942.78", "ansible_distribution_version": "7.9", "facter_sshfp_rsa": "SSHFP 1 1 db5e1cdb600bcf6ee570785d92ad780022b74734\nSSHFP 1 2 03ee11c3d48caf9bc25019abbd7f5c1adc3871789b07fc144609a79a22670232", "ansible_env": {"LANG": "C", "TERM": "xterm", "SHELL": "/bin/bash", "MAIL": "/var/mail/root", "SHLVL": "1", "SSH_TTY": "/dev/pts/0", "LC_CTYPE": "C", "PWD": "/root", "LOGNAME": "root", "USER": "root", "HOME": "/root", "PATH": "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/bin/X11", "SSH_CONNECTION": "10.128.12.23 38784 10.0.160.19 22", "_": "/bin/sh", "SSH_CLIENT": "10.128.12.23 38784 22"}, "facter_lsbmajdistrelease": "7", "facter_gid": "root", "ansible_userspace_bits": "64", "ansible_architecture": "x86_64", "ansible_default_ipv4": {"macaddress": "52:54:00:f4:b1:58", "network": "10.0.160.0", "mtu": 1500, "alias": "eth0", "netmask": "255.255.248.0", "address": "10.0.160.19", "interface": "eth0", "type": "ether", "gateway": "10.0.160.1"}, "ansible_swapfree_mb": 0, "ansible_default_ipv6": {}, "facter_netmask_eth1": "255.255.255.0", "facter_uuid": "199F61FE-7E9C-1B67-2897-1E5513279A7B", "ansible_cmdline": {"root": "/dev/mapper/vs108-root", "ro": true, "BOOT_IMAGE": "/vmlinuz-3.2.0-4-amd64", "quiet": true}, "ansible_selinux": false, "facter_bios_vendor": "Bochs", "ansible_os_family": "Debian", "ansible_userspace_architecture": "x86_64", "facter_blockdevice_vdc_vendor": "0x1af4", "ansible_product_uuid": "199F61FE-7E9C-1B67-2897-1E5513279A7B", "facter_osfamily": "Debian", "facter_blockdevice_vdc_size": 107374182400, "ansible_pkg_mgr": "apt", "facter_filesystems": "btrfs,ext2,ext3,ext4,hfs,hfsplus,jfs,minix,msdos,ntfs,qnx4,reiserfs,ufs,vfat,xfs", "ansible_memory_mb": {"real": {"total": 16086, "free": 15309, "used": 777}, "swap": {"cached": 0, "total": 0, "used": 0, "free": 0}, "nocache": {"used": 133, "free": 15953}}, "ansible_distribution": "Debian", "ansible_user_dir": "/root", "facter_lsbdistrelease": "7.9", "ansible_all_ipv6_addresses": ["fe80::5054:ff:fef4:b158", "fe80::5054:ff:fee2:e7a6"], "facter_blockdevice_vdf_vendor": "0x1af4", "facter_operatingsystemrelease": "7.9", "ansible_kernel": "3.2.0-4-amd64", "facter_blockdevice_vde_size": 107374182400, "facter_os": {"release": {"major": "7", "full": "7.9", "minor": "9"}, "lsb": {"distdescription": "Debian GNU/Linux 7.9 (wheezy)", "distrelease": "7.9", "distid": "Debian", "majdistrelease": "7", "minordistrelease": "9", "distcodename": "wheezy"}, "name": "Debian", "family": "Debian"}, "ansible_user_shell": "/bin/bash", "facter_bios_release_date": "01/01/2007", "facter_architecture": "amd64", "facter_macaddress_eth1": "52:54:00:e2:e7:a6", "facter_lsbminordistrelease": "9", "ansible_product_serial": "NA", "ansible_form_factor": "Other", "facter_blockdevice_vda_size": 10737418240, "facter_fqdn": "vs108.unstable.ipc4.rack.zone", "ansible_fips": false, "facter_system_uptime": {"seconds": 5419130, "hours": 1505, "uptime": "62 days", "days": 62}, "ansible_user_id": "root", "facter_ipaddress_lo": "127.0.0.1", "facter_bios_version": "Bochs", "facter_manufacturer": "Bochs", "facter_memorysize": "15.71 GB", "facter_path": "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/bin/X11", "ansible_processor_vcpus": 4, "facter_network_eth1": "10.0.128.0", "facter_network_eth0": "10.0.160.0", "ansible_processor": ["AuthenticAMD", "QEMU Virtual CPU version 1.1.2", "AuthenticAMD", "QEMU Virtual CPU version 1.1.2", "AuthenticAMD", "QEMU Virtual CPU version 1.1.2", "AuthenticAMD", "QEMU Virtual CPU version 1.1.2"], "facter_is_virtual": "true", "ansible_ssh_host_key_ecdsa_public": "AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBFt+8+TiOHdST7X/h4RKT9dNiM9wi0UsyFZU08uAF9Vz+e6ucc7UXHtKBW5g48qhtYEY2CC1i1C8GHqMXLbzjNc=", "facter_blockdevice_vde_vendor": "0x1af4", "ansible_system_vendor": "Bochs", "facter_blockdevice_vdb_vendor": "0x1af4", "ansible_virtualization_role": "guest", "ansible_swaptotal_mb": 0, "facter_operatingsystemmajrelease": "7", "facter_selinux": "false", "facter_rubyversion": "1.9.3", "ansible_distribution_major_version": "7", "facter_productname": "Bochs", "ansible_lsb": {"release": "7.9", "major_release": "7", "codename": "wheezy", "id": "Debian", "description": "Debian GNU/Linux 7.9 (wheezy)"}, "facter_memoryfree": "15.57 GB", "facter_memorysize_mb": "16086.04", "ansible_machine": "x86_64", "ansible_ssh_host_key_rsa_public": "AAAAB3NzaC1yc2EAAAADAQABAAABAQCzdmbWfFy/f6E9vevHtjA3iKNSWG0OAOPCUgRsJBubj+EF9oKthdvVx88G7ejiDkQJTwJdc5MpqDlrz1Rq7odyjrBL+cd3WEVZpTnApEuIl2E/1MlRJl3PXPAuVCvPZrTnhTLsnW05NgrBMafdDy4+O0aPgPV6L4rPg7VAnFhF79hG1IVlcROI7WqndVywMP27ciR9ABnyPG22zHC/7/vggcByKxyPYpIL44XNTu+xKq/zJCvDbtkbby6eXLJ2xC/1NgioVsPIJTqihgUPf00A/V0Id6HFHoxSuXLaQRHYfaV4Gr/VuwlBN/9NNlTPd0uns/avlPBEClEteOaz9MXp", "facter_ipaddress": "10.0.160.19", "facter_swapsize_mb": "0.00", "ansible_processor_threads_per_core": 1, "facter_serialnumber": "Not Specified", "ansible_eth0": {"macaddress": "52:54:00:f4:b1:58", "module": "virtio_net", "mtu": 1500, "active": true, "promisc": false, "ipv4": {"netmask": "255.255.248.0", "network": "10.0.160.0", "address": "10.0.160.19"}, "ipv6": [{"scope": "link", "prefix": "64", "address": "fe80::5054:ff:fef4:b158"}], "device": "eth0", "type": "ether"}, "ansible_eth1": {"macaddress": "52:54:00:e2:e7:a6", "module": "virtio_net", "mtu": 1500, "active": true, "promisc": false, "ipv4": {"netmask": "255.255.255.0", "network": "10.0.128.0", "address": "10.0.128.19"}, "ipv6": [{"scope": "link", "prefix": "64", "address": "fe80::5054:ff:fee2:e7a6"}], "device": "eth1", "type": "ether"}, "ansible_product_name": "Bochs", "facter_mtu_lo": "16436", "ansible_all_ipv4_addresses": ["10.0.160.19", "10.0.128.19"], "ansible_python_version": "2.7.3", "facter_kernel": "Linux", "facter_sshecdsakey": "AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBFt+8+TiOHdST7X/h4RKT9dNiM9wi0UsyFZU08uAF9Vz+e6ucc7UXHtKBW5g48qhtYEY2CC1i1C8GHqMXLbzjNc=", "facter_blockdevice_vdb_size": 10737418240, "ansible_product_version": "NA", "facter_uptime_seconds": 5419130, "facter_uptime_days": 62, "ansible_memtotal_mb": 16086, "facter_partitions": {"vda5": {"filesystem": "LVM2_member", "size": "20467712"}, "vda1": {"mount": "/boot", "filesystem": "ext2", "uuid": "2e1d092e-836a-4d82-8d40-3d404decadcd", "size": "497664"}, "vda2": {"size": "2"}}, "facter_processor3": "QEMU Virtual CPU version 1.1.2", "facter_processor2": "QEMU Virtual CPU version 1.1.2", "facter_processor1": "QEMU Virtual CPU version 1.1.2", "facter_processor0": "QEMU Virtual CPU version 1.1.2", "facter_rubysitedir": "/usr/local/lib/site_ruby/1.9.1", "facter_macaddress": "52:54:00:f4:b1:58", "facter_kernelmajversion": "3.2", "facter_lsbdistdescription": "Debian GNU/Linux 7.9 (wheezy)", "ansible_lo": {"active": true, "promisc": false, "ipv4": {"netmask": "255.0.0.0", "network": "127.0.0.0", "address": "127.0.0.1"}, "ipv6": [{"scope": "host", "prefix": "128", "address": "::1"}], "device": "lo", "type": "loopback", "mtu": 16436}, "facter_swapsize": "0.00 MB", "facter_blockdevices": "vda,vdb,vdc,vdd,vde,vdf", "facter_facterversion": "2.2.0", "facter_netmask_eth0": "255.255.248.0", "facter_hardwareisa": "unknown", "facter_interfaces": "eth0,eth1,lo", "facter_network_lo": "127.0.0.0", "facter_domain": "unstable.ipc4.rack.zone", "facter_processorcount": "4", "facter_netmask_lo": "255.0.0.0", "facter_swapfree": "0.00 MB", "ansible_memfree_mb": 15309, "facter_mtu_eth1": "1500", "facter_mtu_eth0": "1500", "facter_sshrsakey": "AAAAB3NzaC1yc2EAAAADAQABAAABAQCzdmbWfFy/f6E9vevHtjA3iKNSWG0OAOPCUgRsJBubj+EF9oKthdvVx88G7ejiDkQJTwJdc5MpqDlrz1Rq7odyjrBL+cd3WEVpTnApEuIl2E/1MlRJl3PXPAuVCvPZrTnhTLsnW05NgrBMafdDy4+O0aPgPV6L4rPg7VAnFhF79hG1IVlcROI7WqndVywMP27ciR9ABnyPG22zHC/7/vggcByKxyPYpIL44XNTu+xKq/zJCvDbtkbby6eXLJ2xC/1NgioVsPIJTqihgUPf00A/V0Id6HFHoxSuXLaQRHYfaV4Gr/VuwlBN/9NNlTPd0uns/avlPBEClEteOaz9MXp", "facter_swapfree_mb": "0.00", "facter_processors": {"models": ["QEMU Virtual CPU version 1.1.2", "QEMU Virtual CPU version 1.1.2", "QEMU Virtual CPU version 1.1.2", "QEMU Virtual CPU version 1.1.2"], "count": 4, "physicalcount": 4}, "facter_physicalprocessorcount": "4", "ansible_processor_count": 4, "facter_uniqueid": "007f0101", "ansible_hostname": "vs108", "facter_timezone": "UTC", "facter_sshfp_ecdsa": "SSHFP 3 1 2c0266afd6bb8e168e47dc48c4fde2ae17d560f6\nSSHFP 3 2 9821970d987c90865e249ef9c15b8b6ee4259b8bf766b92d00a003ce7dd1a11d", "ansible_interfaces": ["lo", "eth1", "eth0"], "facter_ipaddress_eth0": "10.0.160.19", "facter_ipaddress_eth1": "10.0.128.19", "facter_virtual": "kvm", "ansible_fqdn": "vs108.unstable.ipc4.rack.zone", "ansible_user_gid": 0, "facter_blockdevice_vdd_vendor": "0x1af4", "facter_ps": "ps -ef", "facter_netmask": "255.255.248.0", "ansible_nodename": "vs108", "ansible_user_gecos": "root", "facter_lsbdistid": "Debian", "ansible_domain": "unstable.ipc4.rack.zone", "ansible_virtualization_type": "kvm", "ansible_processor_cores": 1, "ansible_bios_version": "Bochs", "facter_macaddress_eth0": "52:54:00:f4:b1:58", "ansible_date_time": {"tz": "UTC", "hour": "10", "time": "10:06:00", "tz_offset": "+0000", "month": "11", "epoch": "1446458760", "iso8601_micro": "2015-11-02T10:06:00.589931Z", "weekday": "Monday", "year": "2015", "date": "2015-11-02", "iso8601": "2015-11-02T10:06:00Z", "day": "02", "minute": "06", "second": "00"}, "facter_blockdevice_vda_vendor": "0x1af4", "facter_uptime_hours": 1505, "facter_hostname": "vs108", "ansible_distribution_release": "wheezy", "facter_lsbdistcodename": "wheezy", "ansible_mounts": [{"options": "rw,relatime,errors=remount-ro,user_xattr,barrier=1,data=ordered", "uuid": "f4f055b1-5e58-482b-a577-436cb26e4b0c", "size_total": 9837973504, "device": "/dev/mapper/vs108-root", "mount": "/", "size_available": 8059449344, "fstype": "ext4"}, {"options": "rw,relatime,errors=continue", "uuid": "2e1d092e-836a-4d82-8d40-3d404decadcd", "size_total": 238787584, "device": "/dev/vda1", "mount": "/boot", "size_available": 207684608, "fstype": "ext2"}], "facter_blockdevice_vdd_size": 107374182400, "ansible_system": "Linux", "ansible_devices": {"vda": {"scheduler_mode": "cfq", "rotational": "1", "vendor": "0x1af4", "sectors": "20971520", "host": "SCSI storage controller: Red Hat, Inc Virtio block device", "sectorsize": "512", "removable": "0", "support_discard": "0", "model": null, "size": "10.00 GB", "holders": [], "partitions": {"vda5": {"start": "501760", "sectorsize": 512, "sectors": "20467712", "size": "9.76 GB"}, "vda1": {"start": "2048", "sectorsize": 512, "sectors": "497664", "size": "243.00 MB"}, "vda2": {"start": "501758", "sectorsize": 512, "sectors": "2", "size": "1.00 KB"}}}, "vdc": {"scheduler_mode": "cfq", "rotational": "1", "vendor": "0x1af4", "sectors": "209715200", "host": "SCSI storage controller: Red Hat, Inc Virtio block device", "sectorsize": "512", "removable": "0", "support_discard": "0", "model": null, "size": "100.00 GB", "holders": [], "partitions": {}}, "vdb": {"scheduler_mode": "cfq", "rotational": "1", "vendor": "0x1af4", "sectors": "20971520", "host": "SCSI storage controller: Red Hat, Inc Virtio block device", "sectorsize": "512", "removable": "0", "support_discard": "0", "model": null, "size": "10.00 GB", "holders": [], "partitions": {}}, "vde": {"scheduler_mode": "cfq", "rotational": "1", "vendor": "0x1af4", "sectors": "209715200", "host": "SCSI storage controller: Red Hat, Inc Virtio block device", "sectorsize": "512", "removable": "0", "support_discard": "0", "model": null, "size": "100.00 GB", "holders": [], "partitions": {}}, "vdd": {"scheduler_mode": "cfq", "rotational": "1", "vendor": "0x1af4", "sectors": "209715200", "host": "SCSI storage controller: Red Hat, Inc Virtio block device", "sectorsize": "512", "removable": "0", "support_discard": "0", "model": null, "size": "100.00 GB", "holders": [], "partitions": {}}, "vdf": {"scheduler_mode": "cfq", "rotational": "1", "vendor": "0x1af4", "sectors": "209715200", "host": "SCSI storage controller: Red Hat, Inc Virtio block device", "sectorsize": "512", "removable": "0", "support_discard": "0", "model": null, "size": "100.00 GB", "holders": [], "partitions": {}}}, "ansible_user_uid": 0, "facter_sshfp_dsa": "SSHFP 2 1 7464b1c9ad3c873456ac9ca79111f40fdf4602a2\nSSHFP 2 2 cd38114abd427b996c336da4d297f236755bd8740c0789189c94a41917d6b189", "ansible_ssh_host_key_dsa_public": "AAAAB3NzaC1kc3MAAACBAOJiG7jYVrf3ykE7TMG3+d7qOBbzatWpfkS8TGZ39pAwXQVih63aG2AjwD0dlLhA2+CVdj5vNhC0Xs3hrAbIAxy4WLOMnHcUTvT9R07N0dhjet35xo1qQP368/evXEXsqn3FJS/GHYFR8kMR+aeMuVBQ5RGFTomxt1GP8GtbJpirAAAAFQDqXXHQb4gvjy/nUTvcTzd1NyKEpwAAAIA3u3Sec461mZ4dB16YOfLMOFTOSZTQwFYt24weHX7zlu4dCaJOVl3l6Ol62iFm440epRAogRwVfvGTf0fhD/CrjNwd/AgSEZC5e4eQOwyoym2ntylceyqJQVJ/oyEr80oRZIkSiz6dZPlPCch5zOdUkwD8KklCRS/bbePMsNMNQAAAIA+vF9j8ZboluGLERMfsSwV9+6M9joPiSv7HcOlZ2KUuIV3VXspXdcZsgy+Cb/elvktRZ+Ufe8doxogzn1pVuvJJpo/6AfH4jkZFs8a8T90Tq+/2TdYCBYjwV3pEtzyRYa7yW1fGtJI5w3tsZkW1w5qgafPP++2T5KI+RenKw9rvQ==", "ansible_bios_date": "01/01/2007", "facter_uptime": "62 days", "facter_kernelrelease": "3.2.0-4-amd64", "facter_kernelversion": "3.2.0", "facter_hardwaremodel": "x86_64", "facter_sshdsakey": "AAAAB3NzaC1kc3MAAACBAOJiG7jYVrf3ykE7TMG3+d7qOBbzatWpfkS8TGZ39pAwXQVih63aG2AjwD0dlLhA2+CVdj5vNhC0Xs3hrAbIAxy4WLOMnHcUTvT9R07N0dhjet35xo1qQP368/evXEXsqn3FJS/GHYFR8kMR+aeMuVBQ5RGFTomxt1GP8GtbJpirAAAAFQDqXXHQb4gvjy/nUTvcTzd1NyKEpwAAAIA3u3Sec461mZ4dB16YOfLMOFTOSZTQwFt24weHX7zlu4dCaJOVl3l6Ol62iFm440epRAogRwVfvGTf0fhD/CrjNwd/AgSEZC5e4eQOwyoym2ntylceyqJQVJ/oyEr80oRZnIkSiz6dZPlPCch5zOdUkwD8KklCRS/bbePMsNMNQAAAIA+vF9j8ZboluGLERMfsSwV9+6M9joPiSv7HcOlZ2KUuIV3VXspXdcZsgy+Cb/elvktRZ+Ufe8doxogzn1pVuvJJpo/6AfH4jkZFs8a8T90Tq+/2TdYCBYjwV3pEtzyRYa7yW1fGtJI5w3tsZkW1w5qgafPP++2T5KI+RenKw9rvQ==", "facter_id": "root", "facter_type": "Other"}}
}

**Comment by dLobatog** [comment]
This just means the plugin is not installed yet on the Foreman host, and it's using the Puppet fact importer - which only recognizes these 3 facts.
